version: '3.7'

services:
  saml-idp:
    container_name: saml-idp
    image: kristophjunge/test-saml-idp
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: 'saml-poc'
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: 'http://localhost:8000/login/callback'
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: 'http://localhost:8000/logout/callback'
    ports:
      - 8080:8080
      - 8443:8443