version: '3.7'

services:
  saml-idp:
    container_name: saml-idp
    image: kristophjunge/test-saml-idp
    volumes:
      - ./saml20-sp-remote.php:/var/www/simplesamlphp/metadata/saml20-sp-remote.php
    ports:
      - 8080:8080
      - 8443:8443